"""baseline

Revision ID: 5b91174760ea
Revises:
Create Date: 2026-05-05 19:00:33.504648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b91174760ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('pin_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_pin_reset', sa.Boolean(), nullable=False),
    sa.Column('last_pin_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_email'), 'guardians', ['email'], unique=True)
    op.create_index(op.f('ix_guardians_id'), 'guardians', ['id'], unique=False)
    op.create_index(op.f('ix_guardians_phone_number'), 'guardians', ['phone_number'], unique=False)
    op.create_index(op.f('ix_guardians_pin_updated_at'), 'guardians', ['pin_updated_at'], unique=False)
    op.create_index(op.f('ix_guardians_public_id'), 'guardians', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PROVIDER', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('facility_address', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_license_number'), 'users', ['license_number'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('guardian_pin_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('verification_method', sa.Enum('SMS_OTP', 'EMAIL_OTP', name='resetverificationmethods'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', name='resetstatuses'), nullable=False),
    sa.Column('reset_code_hash', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_pin_resets_created_at'), 'guardian_pin_resets', ['created_at'], unique=False)
    op.create_index(op.f('ix_guardian_pin_resets_expires_at'), 'guardian_pin_resets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_guardian_pin_resets_guardian_id'), 'guardian_pin_resets', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_guardian_pin_resets_id'), 'guardian_pin_resets', ['id'], unique=False)
    op.create_index(op.f('ix_guardian_pin_resets_public_id'), 'guardian_pin_resets', ['public_id'], unique=True)
    op.create_index(op.f('ix_guardian_pin_resets_requested_by_user_id'), 'guardian_pin_resets', ['requested_by_user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NA', name='genders'), nullable=False),
    sa.Column('medical_note', sa.String(length=350), nullable=True),
    sa.Column('state_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_provider_id'), 'students', ['provider_id'], unique=False)
    op.create_index(op.f('ix_students_public_id'), 'students', ['public_id'], unique=True)
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.Enum('CHECK_IN', 'CHECK_OUT', 'ABSENT', name='actions'), nullable=False),
    sa.Column('entry_type', sa.Enum('GUARDIAN', 'PROVIDER', name='entrytypes'), nullable=False),
    sa.Column('authorized_person_name', sa.String(length=200), nullable=True),
    sa.Column('guardian_signature_url', sa.String(length=512), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('original_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['original_log_id'], ['attendance_logs.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_created_at'), 'attendance_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_logs_event_time'), 'attendance_logs', ['event_time'], unique=False)
    op.create_index(op.f('ix_attendance_logs_guardian_id'), 'attendance_logs', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_id'), 'attendance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_provider_id'), 'attendance_logs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_public_id'), 'attendance_logs', ['public_id'], unique=True)
    op.create_index(op.f('ix_attendance_logs_student_id'), 'attendance_logs', ['student_id'], unique=False)
    op.create_table('attendance_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_notes_attendance_date'), 'attendance_notes', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_notes_id'), 'attendance_notes', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_notes_provider_id'), 'attendance_notes', ['provider_id'], unique=False)
    op.create_index(op.f('ix_attendance_notes_public_id'), 'attendance_notes', ['public_id'], unique=True)
    op.create_index(op.f('ix_attendance_notes_student_id'), 'attendance_notes', ['student_id'], unique=False)
    op.create_table('student_guardian_links',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('relationship_to_student', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'guardian_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_guardian_links')
    op.drop_index(op.f('ix_attendance_notes_student_id'), table_name='attendance_notes')
    op.drop_index(op.f('ix_attendance_notes_public_id'), table_name='attendance_notes')
    op.drop_index(op.f('ix_attendance_notes_provider_id'), table_name='attendance_notes')
    op.drop_index(op.f('ix_attendance_notes_id'), table_name='attendance_notes')
    op.drop_index(op.f('ix_attendance_notes_attendance_date'), table_name='attendance_notes')
    op.drop_table('attendance_notes')
    op.drop_index(op.f('ix_attendance_logs_student_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_public_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_provider_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_guardian_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_event_time'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_created_at'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_students_public_id'), table_name='students')
    op.drop_index(op.f('ix_students_provider_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_guardian_pin_resets_requested_by_user_id'), table_name='guardian_pin_resets')
    op.drop_index(op.f('ix_guardian_pin_resets_public_id'), table_name='guardian_pin_resets')
    op.drop_index(op.f('ix_guardian_pin_resets_id'), table_name='guardian_pin_resets')
    op.drop_index(op.f('ix_guardian_pin_resets_guardian_id'), table_name='guardian_pin_resets')
    op.drop_index(op.f('ix_guardian_pin_resets_expires_at'), table_name='guardian_pin_resets')
    op.drop_index(op.f('ix_guardian_pin_resets_created_at'), table_name='guardian_pin_resets')
    op.drop_table('guardian_pin_resets')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_license_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guardians_public_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_pin_updated_at'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_phone_number'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_email'), table_name='guardians')
    op.drop_table('guardians')
    # ### end Alembic commands ###
