# Implement core CRUD for User, Student, Guardian, and link-table operations.
#   2. Add attendance CRUD/service functions next.
#      Include check-in, check-out, mark absent, manual entry, correction, and day-status queries.
#   3. Add guardian PIN reset CRUD flows.
#      Request reset, verify code, complete reset with new PIN.
#   4. Once CRUD is stable, initialize Alembic and create the first migration.
#   5. Then add Pytest with DB/session fixtures and smoke tests for the core CRUD paths.

# def create_user(db: Session, user: UserCreate):
#     """Creates a new user record in the database."""
#     fake_hashed_password = user.password + "notreallyhashed"
#     db_user = User(email=user.email, hashed_password=fake_hashed_password)
#     db.add(db_user)
#     db.commit()
#     db.refresh(db_user)
#     return db_user

import bcrypt
import uuid
from sqlalchemy import select
from sqlalchemy.orm import Session

from . import models, schemas

def hash_secret(secret: str) -> str:
    """Hash a secret (password/PIN) using bcrypt."""
    hashed = bcrypt.hashpw(secret.encode("utf-8"), bcrypt.gensalt(rounds=12))
    return hashed.decode("utf-8")

def verify_secret(plain: str, hashed: str) -> bool:
    """Verify a plain secret against a bcrypt hash."""
    return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))

def create_user(db: Session, user: schemas.UserCreate) -> models.User:
    db_user = models.User(
        email=user.email,
        first_name=user.first_name,
        last_name=user.last_name,
        profile_picture=user.profile_picture,
        role=user.role,
        facility_name=user.facility_name,
        facility_address=user.facility_address,
        license_number=user.license_number,
        hashed_password=hash_secret(user.password),
        hashed_pin=hash_secret(user.pin),
    )
    db.add(db_user)
    # Intentionally do not commit here. CRUD functions should be composable so a
    # service / API layer can wrap multiple operations in a single transaction.
    #
    # We still flush so autogenerated PKs/defaults (id/public_id, etc.) are
    # available to the caller within the ongoing transaction.
    db.flush()
    return db_user

def get_user(db: Session, user_id: int) -> models.User | None:
    """Return one user by internal database id."""
    return db.get(models.User, user_id)

def get_user_by_public_id(db: Session, public_id: uuid.UUID) -> models.User | None:
    """Return one user by stable public id."""
    statement = select(models.User).where(models.User.public_id == public_id)
    return db.scalars(statement).one_or_none()

def get_user_by_email(db: Session, email: str) -> models.User | None:
    """Return one user by unique email address."""
    statement = select(models.User).where(models.User.email == email.lower())
    return db.scalars(statement).one_or_none()
